apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0e787541e27feaf94
    fsType: ext4
