apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0923872fb220a9238
    fsType: ext4

