apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-07028e0f8b7125344
    fsType: ext4
