apiVersion: v1
kind: Pod
metadata:
  name: aish-nodeaffinitypod
spec:
  containers:
  - name: container-nodeselector5
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: Exists

