kind: Pod
apiVersion: v1
metadata:
  name: nodeaffinitypod
  namespace: aishns
  labels:
    env: development
    class: pods
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - t2.micro
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - t3.micro
  containers:
  - name: container-nodeselector5
    image: nginx:latest
    ports:
    - containerPort: 80
