apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: default
  labels: 
    env: development
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - containerPort: 80